Use External EbsdLib and H5Support Libraries
BlueQuartzSoftware/EbsdLib pull request #3
Opened 2020-04-03 16:17 UTC by imikejackson

2020-04-07 15:19 UTC, mmarineBlueQuartz commented on Source/EbsdLib/IO/AngleFileLoader.cpp
> +      sigma = tokens[4].trimmed().toFloat(&ok);
If you aren't checking ok, use the default parameter value (nullptr).
This applies to later uses as well as this method has a number of them.

2020-04-07 19:40 UTC, mmarineBlueQuartz requested changes
The unused ok variable in AngleFileLoader is the only thing that stuck out to me.  It's inclusion signifies that it serves some purpose, but its value is never used or checked. The assignment is optional which leads me to believe the variable should be removed.

2020-04-10 20:13 UTC, imikejackson commented
Updated AngleFileLoader with proper error checking

2020-04-10 20:16 UTC, mmarineBlueQuartz approved these changes

2020-04-13 12:30 UTC, closed without merging